server:
  port: 8080
  display-name: OWNER
  context-path: /
  jsp-servlet:
    init-parameters:
      development: true
  session:
    timeout: 1800

info:
  version: "1.0.0"
mybatis:
  mapperLocations: classpath:mapper/**/*Mapper.xml


spring:
#  mvc:
#    static-path-pattern: /static/**
  profiles:
    include: druid, redis, rescode
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  jackson:
    time-zone: GMT+8


#mybatis日志输出
logging:
  level:
    com.cy.owner.dao: debug
    org:
      mybatis: debug
