server:
  port: 8080
  servlet:
    context-path: /
    application-display-name: OWNER
    session:
      timeout: 1800

info:
  version: "1.0.0"
mybatis:
  typeAliasesPackage: priv.cy.owner.entity.**
  mapper-locations: classpath:/mapperXml/**/*Mapper.xml


spring:
  #  mvc:
  #    static-path-pattern: /static/**
  profiles:
    include: druid, redis, rescode
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  jackson:
    time-zone: GMT+8


#mybatis日志输出
logging:
  level:
    com.cy.owner.dao: debug
    org:
      mybatis: debug
