server:
  port: 8080
  servlet:
    context-path: /
    application-display-name: OWNER
    session:
      timeout: 1800

info:
  version: "1.0.0"
mybatis:
  typeAliasesPackage: priv.cy.owner.entity.**
  mapper-locations: classpath:/mapperXml/**/*Mapper.xml


spring:
  #  mvc:
  #    static-path-pattern: /static/**
  profiles:
    include: druid, redis, rescode, activemq
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  jackson:
    time-zone: GMT+8


#mybatis日志输出
logging:
  level:
    com.cy.owner.dao: debug
    org:
      mybatis: debug

token:
  #  token过期时间，单位分钟
  tokenExpireTime: 120
  #  RefreshToken过期时间，单位：分钟, 24*60=1440
  refreshTokenExpireTime: 1440
  #  shiro缓存有效期，单位分钟,2*60=120
  shiroCacheExpireTime: 120
  #  token加密密钥
  secretKey: storywebkey

#可匿名访问的链接
jwt:
  anonymous:
    urls: sysuser/login, sysuser/lgout
