spring:
  activemq:
    broker-url: tcp://39.108.254.80:61616
  user: admin
  password: admin
  #这里简单对这个配置说明下：如果为True，则是Topic；如果是false或者默认，则是queue。
  jms:
    pub-sub-domain: true
    pool:
      enabled: false
      maxConnections: 2
      expiryTimeout: 0
      idleTimeout: 30000
  packages:
    trust-all: true


